[project]
name = "python-practice"
version = "0.1.0"
description = ""
authors = [
    {name = "duxatici",email = "istouched@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4 (>=0.0.2,<0.0.3)",
    "sqlalchemy (>=2.0.50,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "lxml (>=6.1.1,<7.0.0)",
    "pdfplumber (>=0.11.9,<0.12.0)",
    "aiohttp (>=3.14.1,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = ["."]
