[project]
name = "python-practice"
version = "0.1.0"
description = ""
authors = [
    {name = "duxatici",email = "istouched@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4 (>=0.0.2,<0.0.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = ["."]
