# Generated by Django 6.0.6 on 2026-06-19 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео"},
        ),
        migrations.AlterModelOptions(
            name="videofile",
            options={
                "verbose_name": "Видео файл",
                "verbose_name_plural": "Видео файлы",
            },
        ),
        migrations.AlterField(
            model_name="like",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="videos.video",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="video",
            name="total_likes",
            field=models.IntegerField(default=0, verbose_name="Лайки"),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("video", "user"), name="unique_likes"
            ),
        ),
    ]
