# Generated by Django 6.0.6 on 2026-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_alter_video_options_alter_videofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="quality",
            field=models.CharField(
                choices=[("HD", "HD"), ("FHD", "Full HD"), ("UHD", "Ultra HD")],
                default="HD",
                max_length=3,
                verbose_name="Качество видео",
            ),
        ),
    ]
