# Generated by Django 6.0.6 on 2026-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_alter_videofile_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="file",
            field=models.FileField(upload_to="", verbose_name="Путь к файлу"),
        ),
    ]
