"""initial

Revision ID: e23d2673f588
Revises:
Create Date: 2026-07-14 17:39:03.501321

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e23d2673f588"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
